.TH Sniffjoke
.PP
.SH NAME
Sniffjoke 0.4 usage
.PP
.SH SYNOPSIS
sniffjoke --option
.PP
.SH DESCRIPTION
This software is a single peer sniffer obfuscator. when you start SniffJoke
from your network privileges, the outgoing internet connections became
scattered with fake data - without interfere with your sessions - and confusing
the sniffers in the network when their algorithms try to follow your stream.
.PP
.B sniffjoke --help
this command returns three piece of information,
.PP
The option usefull when sniffjoke is started (by hand or by init script)
.PP
.PP
.B sniffjoke 
[command] or 
.B sniffjoke --options:
.PP
.B --location <name> 
specify the network environment (suggested) [default: generic]
.PP
.B --dir <name> 
specify the base directory where the location reside [default: /usr/local/var/sniffjoke/] [using both location and dir defaults, the configuration status will not be saved]
.PP
.B --user <username> 
downgrade priviledge to the specified user [default: nobody]
.PP
.B --group <groupname> 
downgrade priviledge to the specified group [default: nogroup]
.PP
.B --whitelist 
inject evasion packets only in the specified ip addresses
.PP
.B --blacklist 
inject evasion packet in all session excluding the blacklisted ip address
.PP
.B --start 
if present, evasion i'ts activated immediatly [default: not present]
.PP
.B --debug <level 1-6> 
set up verbosoty level [default: 2] 1: suppress log, 2: common, 3: verbose, 4: debug, 5: session 6: packets
.PP
.B --foreground 
running in foreground [default:background]
.PP
.B --admin <ip>[:port] 
specify administration IP address [default: 127.0.0.1:8844]
.PP
.B --force 
force restart (usable when another sniffjoke service is running)
.PP
.B --version 
show sniffjoke version
.PP
.B --help 
show this help
.PP
.PP
When sniffjoke is running keep on memory the configuration settings and dump them in a binary file, sniffjoke run under chroot directory and inside them there are files usefull for sniffjoke and for the user.
.PP
.PP
And this is the sniffjoke manage, controller, client, whaterver:
.PP
.PP
.B sniffjokectl --options 
[command]:
.PP
.B --address <ip>[:port] 
specify administration IP address [default: 127.0.0.1:8844]
.PP
.B --version show 
sniffjoke version
.PP
.B --timeout 
set milliseconds timeout when contacting SniffJoke service [default: 500]
.PP
.B --help 
show this help
.PP
When sniffjoke is running, you should send commands with a command line argument:
.PP
.PP
.B start 
start sniffjoke hijacking/injection
.PP
.B stop 
stop sniffjoke (but remain tunnel interface active)
.PP
.B quit 
stop sniffjoke, save config, abort the service
.PP
.B saveconf 
dump config file
.PP
.B stat 
get statistics about sniffjoke configuration and network
.PP
.B info 
get massive info about sniffjoke internet stats
.PP
.B showport 
show TCP ports strongness of injection
.PP
.B debug [1-6] 
change the log debug level
.PP
.PP
Those command are used and accepted only when sniffjoke is running and the "client instance" is listening and reachable in the UDP port.
.PP
When you set your port rules, save the configuration with saveconf and continue to use sniffjoke. when you restart sniffjoke, using the same --chroot-dir, the previous configurations are reloaded.
.PP

.SS SEMI-SECRET OPTION 
This semi-secret option is used in testing within sniffjoke-autotest
.PP
.B    --only-plugin 
plugin_name.so,SINGLESCRAMBLEUSED
.PP
.PP
.SS [*] DEFAULTS:

The default values are hardcoded in the software, passed at compile time from the building script, maybe a distribution-specific package will contain different paths.
.PP
.SH AUTHOR
Claudio Agosti <vecna@delirandom.net> Giovanni Pellerano <evilaliv3@evilaliv3.org>

