#!/bin/sh -x

start_singletest() {
	TESTID=`echo "sj_$OS_$x_$y"`
	echo "$PLUGIN e $SCRAMBLE e $TESTID e $PPATH"
	echo "+ Starting sniffjoke with $nowplug and $nowscramb and server $SERVER (test ID: $TESTID)"
	$SNIFFJOKEBIN --debug 1 --chroot-dir /tmp/$TESTID --only-plugin $nowplug --scramble $nowscramb
	$SNIFFJOKEBIN set 80 80 heavy 
	$SNIFFJOKEBIN start 
	cd /tmp/$TESTID
	# $SERVER is like http://www.delirandom.net/sniffjoke_test/post_echo.php
	curl -d "sparedata=`cat $GENERATEDFILE`" $server > received_echo
	CHECKSUM=`md5sum $GENERATEDFILE | cut -b -32`
	sniffjoke quit
	echo "* checksum to compare $VERIFTYSUM | $CHECKSUM"
	cd ..
}

echo "Sniffjoke testsuite test every default plugin with every scrambling tech"

USERID=`id -u`
if [ $USERID != "0" ]; then
	echo "- Error, only root should run $0"
	exit;
fi

SNIFFJOKEBIN="/usr/local/bin/sniffjoke"

if [ ! -x $SNIFFJOKEBIN ]; then
	echo "$SNIFFJOKEBIN is not a valid executable"
	exit;
fi

echo "+ Starting SniffJoke hacks test"
echo "* Stopping running sniffjoke ($SNIFFJOKEBIN quit)"
$SNIFFJOKEBIN quit

PPATH="/usr/local/lib/sniffjoke"

plugins=( fake_close_fin.so fake_close_fin.so fake_close_rst.so fake_data.so fake_seq.so fake_syn.so fake_zero_window.so shift_ack.so valid_rst_fake_seq.so )

scrambling=(YNN NYN NNY)

FILEURL="http://www.delirandom.net/sniffjoke/testsuite.info"
echo "retrivering multi-OS testing server list ($FILEURL)"
SERVERFILE="/tmp/testsuite.info"
rm -f $SERVERFILE
wget -O $SERVERFILE $FILEURL

if ! [ -e $SERVERFILE ]; then
	echo "- unable to retriver $SERVERFILE by wget $FILEURL"
	exit;
fi

# generate the test file
GENERATEDFILE="/tmp/tosend_data.generated"
seq 1000 3000 > $GENERATEDFILE
VERIFYSUM=`md5sum $GENERATEDFILE | cut -b -32`

for PLUGIN in ${plugins[@]}; do
	for SCRAMBLE in ${scrambling[@]}; do

		OS="WINDOWS"
		SERVER=`cat "$SERVERFILE" | grep "$OS" | cut -b 9-`
		echo $SERVER
		start_singletest 

		OS="LINUX"
		SERVER=`grep "$OS=" $SERVERFILE | cut -b 7-`
		echo $SERVER
		start_singletest 

		OS="OTHER"
		SERVER=`grep "$OS=" $SERVERFILE | cut -b 7-`
		echo $SERVER
		start_singletest 
	done
done
