#!/bin/sh 

start_singletest() {
	TESTID="sj_$OS_$x_$y"
	echo "$PLUGIN e $SCRAMBLE e $TESTID"
	echo "+ Starting sniffjoke with $nowplug and $nowscramb and server $SERVER (test ID: $TESTID)"
	$SNIFFJOKEBIN --debug 6 --chroot-dir /tmp/$id --plugin $nowplug,$nowscramb
	$SNIFFJOKEBIN set 80 80 heavy 
	$SNIFFJOKEBIN start 
	pushd /tmp/$id
	# $SERVER is like http://www.delirandom.net/sniffjoke_test/post_echo.php
	curl -d "sparedata=`cat $GENERATEDFILE`" $server > received_echo
	CHECKSUM=´md5sum $GENERATEDFILE | cut -b -32´
	sniffjoke quit
	echo "* checksum to compare $VERIFTYSUM | $CHECKSUM"
	popd
}

echo "Sniffjoke testsuite test every default plugin with every scrambling tech"

USERID=`id -u`
if [ $USERID != "0" ]; then
	echo "- Error, only root should run $0"
	exit;
fi

SNIFFJOKEBIN="/usr/local/bin/sniffjoke"

if [ ! -x $SNIFFJOKEBIN ]; then
	echo "$SNIFFJOKEBIN is not a valid executable"
	exit;
fi

echo "+ Starting SniffJoke hacks test"
echo "* Stopping running sniffjoke ($SNIFFJOKEBIN quit)"
$SNIFFJOKEBIN quit

plugins[0]="/usr/local/lib/sniffjoke/fake_close_fin.so"
plugins[1]="/usr/local/lib/sniffjoke/fake_close_rst.so"
plugins[2]="/usr/local/lib/sniffjoke/fake_data.so"
plugins[3]="/usr/local/lib/sniffjoke/fake_seq.so"
plugins[4]="/usr/local/lib/sniffjoke/fake_syn.so"
plugins[5]="/usr/local/lib/sniffjoke/fake_zero_window.so"
plugins[6]="/usr/local/lib/sniffjoke/shift_ack.so"
plugins[7]="/usr/local/lib/sniffjoke/valid_rst_fake_seq.so"

scrambling[0]="YNN"
scrambling[1]="NYN"
scrambling[2]="NNY"

FILEURL="http://www.delirandom.net/sniffjoke/testsuite.info"
echo "retrivering multi-OS testing server list ($FILEURL)"
SERVERFILE="/tmp/testsuite.info"
rm -f $SERVERFILE
wget -O $SERVERFILE $FILEURL

if [ -ne $SERVERFILE ]; then
	echo "- unable to retriver $SERVERFILE by wget $FILEURL"
	exit;
fi

plug_i=`seq 0 7` 
scramb_i=`seq 0 2`

# generate the test file
GENERATEDFILE="/tmp/tosend_data.generated"
seq 1000 3000 > $GENERATEDFILE
VERIFYSUM=`md5sum $GENERATEDFILE | cut -b -32`

for x in $plug_i; do
	for y in $scramb_i; do
		PLUGIN={plugins[$x]}
		SCRAMBLE={scrambling[$y]}

		OS="WINDOWS"
		SERVER=`cat "$SERVERFILE" | grep "$OS" | cut -b 9-`
		start_singletest 

		OS="LINUX"
		SERVER=`grep "$OS=" $SERVERFILE | cut -b 7-`
		start_singletest 

		OS="OTHER"
		SERVER=`grep "$OS=" $SERVERFILE | cut -b 7-`
		start_singletest 
	done
done
